appearance = "system"
theme_dark = "gruvbox-dark"
theme_light = "github-light"

diff_view = "side-by-side"
ignore_whitespace = false
show_file_list = true
mouse = true
leader = " "
comment_vim = true
