#!/bin/bash
# -*-mode:bash-*- vim:ft=bash
#
# ~/.bash_functions
# ====================================
#
# Executed for non-login shells.
#

# If not running interactively, don't do anything.
case $- in
*i*) ;;
*) return ;;
esac


# Print path to command if exist
function cmd_path() {
  if [[ $ZSH_VERSION ]]; then
    whence -cp "$1" 2> /dev/null
  else  # bash
     type -P "$1"  # No output if not in $PATH
  fi
}

#
# Alias helper functions
#
#
function __remove_alias() {
  local CMDTYPE=$(type "$1") 
  case $CMDTYPE in
    *"alias"*)
      unalias $1 2> >(grep -Ev 'no such hash table element' >&2)
    ;;
    *"function"*)
      echo -e "\u001b[34mError: alias is a function\u001b[0m"
    ;;
    *"not found"*)
    ;;
    *)
      echo -e "Error: unknown command type for $1 return message is '$CMDTYPE'"
    ;;
  esac
}
function __alias () {
  __remove_alias "$1"
  alias "$1"="$2"
}

# Print paths on new line and count
function syspath(){
   echo $PATH | sed 's/:/\n/g' | sort | uniq -c
}

# Runtime home directory for asdf managed language runtimes
function runtime_homedir(){
  asdf where ${1} $(asdf current ${1} | awk '{ print $2 }')
}

# Change directory to folder in workspace folder
function ws() {
  workspace=$(fd --type d -uu -a . "$HOME/ws" | fzf)
  cd $workspace
}

# Open Marked 2, passing provided file path to the application
function marked() {
  if [ -n "${1}" ]; then
    open -a "Marked 2" "${1}"
  else
    open -a "Marked 2"
  fi
}

# Print the difference between the target state and the destination state for
# targets. If no targets are specified, print the differences for all targets.
function chezmoidiff() {
  if [ -n "${1}" ]; then
    chezmoi diff --format=git "${1}" | delta
  else
    chezmoi diff --format=git
  fi
}

# Install requirements.txt in conda environment
#
# Original solution via StackOverflow: 
# http://stackoverflow.com/questions/35802939/install-only-available-packages-using-conda-install-yes-file-requirements-t
#
function conda_install_requirements() {
  #  Install via `conda` directly.
  #  This will fail to install all
  #  dependencies. If one fails,
  #  all dependencies will fail to install.
  conda install --yes --file requirements.txt

  #
  #  To go around issue above, one can
  #  iterate over all lines in the
  #  requirements.txt file.
  while read requirement; do conda install --yes $requirement; done < requirements.txt 
}

# using ripgrep combined with preview
# find-in-file - usage: fif <searchTerm>
# reference: https://github.com/junegunn/fzf/wiki/examples#searching-file-contents
function fif() {
  if [ ! "$#" -gt 0 ]; then
    echo "Need a string to search for!"
    return 1
  fi
  rg --files-with-matches --no-messages "$1" | fzf --preview "highlight -O ansi -l {} 2> /dev/null | rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '$1' || rg --ignore-case --pretty --context 10 '$1' {}"
}

# an alternative to the above using ripgrep-all (rga)
function fid() {
  if [ ! "$#" -gt 0 ]; then
    echo "Need a string to search for!"
    return 1
  fi
  rga --files-with-matches --no-messages "$1" | fzf --preview "highlight -O ansi -l {} 2> /dev/null | rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '$1' || rg --ignore-case --pretty --context 10 '$1' {}"
}

# fbr - checkout git branch (including remote branches), sorted by most recent commit, limit 30 last branches
# reference: https://github.com/junegunn/fzf/wiki/examples#git
function fbr() {
  local branches branch
  branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)") &&
    branch=$(echo "$branches" |
      fzf-tmux -d $((2 + $(wc -l <<<"$branches"))) +m) &&
    git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

__alias glNoGraph='git log --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr% C(auto)%an" "$@"'
_gitLogLineToHash="echo {} | grep -o '[a-f0-9]\{7\}' | head -1"
_viewGitLogLine="$_gitLogLineToHash | xargs -I % sh -c 'git show --color=always % | diff-so-fancy'"

# fcoc_preview - checkout git commit with previews
function fcoc_preview() {
  local commit
  commit=$(glNoGraph |
    fzf --no-sort --reverse --tiebreak=index --no-multi \
      --ansi --preview="$_viewGitLogLine") &&
    git checkout $(echo "$commit" | sed "s/ .*//")
}

# fshow_preview - git commit browser with previews
function fshow_preview() {
  glNoGraph |
    fzf --no-sort --reverse --tiebreak=index --no-multi \
      --ansi --preview="$_viewGitLogLine" \
      --header "enter to view, alt-y to copy hash" \
      --bind "enter:execute:$_viewGitLogLine   | less -R" \
      --bind "alt-y:execute:$_gitLogLineToHash | xclip"
}

# fcs - get git commit sha
# example usage: git rebase -i `fcs`
function fcs() {
  local commits commit
  commits=$(git log --color=always --pretty=oneline --abbrev-commit --reverse) &&
    commit=$(echo "$commits" | fzf --tac +s +m -e --ansi --reverse) &&
    echo -n $(echo "$commit" | sed "s/ .*//")
}

# Check the content length of a file and print size in MB
function contentlength() {
  if [[ ! -z "$1" ]]; then
    curl -sLI $1 | awk 'tolower($1) ~ /content-length/ {print $1, ($2/1000000), "MB"}'
  else
    echo "Enter URL to file"
  fi
}

function viml() {
  if [[ -f "$LAST_NVIM_SESSION" ]]; then
    lvim -S $LAST_NVIM_SESSION
  else
    echo "Last lvim session not found at $LAST_NVIM_SESSION"
    touch $LAST_NVIM_SESSION
    echo "Made a new file"
  fi
}

function vims() {
  SESSION=$(fd . -a $NVIM_SESSION | fzf)
  lvim -S "$SESSION"
}

function updatenvim() {
  echo ".  .     .    ,     .  .     .  .      ";
  echo "|  |._  _| _.-+-_   |\ | _  _\  /*._ _ ";
  echo "|__|[_)(_](_] |(/,  | \|(/,(_)\/ |[ | )";
  echo "    |                                  ";

  echo -e '  \u001b[34mInstalling, updating and cleaning neovim plugins\u001b[0m'
  echo -e '============================================================'
  {
    nvim "+call minpac#update('', {'do': 'quitall'})"
  } || { echo -e '  \u001b[31mError updating minpac\u001b[0m'; }
  sleep 2s
  { 
    conda update -n base --all --yes
    npm update -g neovim
    brew reinstall -q nvim
  } && { 
    echo -e '  \u001b[34m\n============================================================\u001b[0m'; 
  }
  echo
  # ASCII art by http://patorjk.com/software/taag/#p=display&h=1&c=echo&f=Contessa&t=Update%20NeoVim
}

function updatetmux() {
  echo "                                                                     ";
  echo " | | ._   _|  _. _|_  _    _|_ ._ _           ._  |      _  o ._   _ ";
  echo " |_| |_) (_| (_|  |_ (/_    |_ | | | |_| ><   |_) | |_| (_| | | | _> ";
  echo "     |                                        |          _|          ";
  echo -e '  \u001b[34mUpdate all tmux plugins\u001b[0m'
  echo -e '  \u001b[34mTPM updating plugins\u001b[0m'
  echo -e '==========================='

  if $HOME/.tmux/plugins/tpm/bin/update_plugins all; then
    echo -e '==========================='
    echo -e '  \u001b[34mTMUX plugins updated\u001b[0m'
    if tmux source-file $HOME/.tmux.conf; then
      echo -e '  \u001b[34mSourced tmux config\u001b[0m'
    else
      echo -e '  \u001b[34mError sourcing tmux configuration\u001b[0m'
    fi
  else
    echo -e '==========================='
    echo -e '  \u001b[34mError updating tmux plugins\u001b[0m'
    echo -e '  \u001b[34mvisit: https://github.com/tmux-plugins/tpm/blob/master/docs/managing_plugins_via_cmd_line.md\u001b[0m'
  fi
}

function updatezshcustom() {
  printf "\n${BLUE}%s${RESET}\n" "Updating custom plugins and themes"
  cd $ZSH_CUSTOM
  for plugin in plugins/*/ themes/*/; do
    if [ -d "$plugin/.git" ]; then
      printf "${YELLOW}%s${RESET}\n" "${plugin%/}"
      git -C "$plugin" pull
    fi
  done
}

# Check if the function exists (bash specific)
#[ -z "$1" ] || {
#  if declare -f "$1" > /dev/null
#  then
#    # call arguments verbatim
#    "$@"
#  else
#    # Show a helpful error
#    echo "'$1' is not a known function name" >&2
#    exit 1
#  fi
#}
