[mgr]
show_hidden = true

[preview]
wrap = "yes"

[plugin]
prepend_previewers = [
    { url = "*.md", run = "mdcat" },
    { mime = "text/csv", run = "mlr"},
    # Archive previewer
    { mime = "application/zip",           run = "ouch" },
    { mime = "application/tar",           run = "ouch" },
    { mime = "application/bzip2",         run = "ouch" },
    { mime = "application/7z-compressed", run = "ouch" },
    { mime = "application/rar",           run = "ouch" },
    { mime = "application/xz",            run = "ouch" },
]

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
