#inherits = "github_dark_tritanopia"
inherits = "github_light_high_contrast"

"mine.black"                      = "#0E1825" 
"mine.grey"                       = "#2F677C"

"ui.statusline.normal"            = { fg = "fg.default", bg = "accent.muted" }
"ui.statusline.separator"         = { fg = "accent.muted" }
